baseURL = "https://marinmg.github.io"
languageCode = "en-us"
title = "Gabriel Marin"
theme = "beautifulhugo"
license = "MIT"
publishDir = "docs"
enableEmoji = true

[Params]
    rss = true
    favicon = "./static/images/favicon.ico"
    mainSections = ["post","posts"]

[Params.author]
    name = "Gabriel Marin"
    email = "mihaigmarin@gmail.com"
    website = "https://marinmg.github.io"
    github = "https://github.com/marinmg"
    linkedin = "https://linkedin.com/in/maringabriel"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
